input_dir: "examples"
output_viewshed_dir: "examples/output/viewshed"
output_horizon_dir: "examples/output/horizon"
output_detection_dir: "examples/output/detection"
cache_dir: "data_cache"
altitudes_msl_m: [100]
target_altitude_reference: "agl"
sensor_height_m_agl: 10.0
max_radius_km: 30
detection_ranges: [20]
union_outputs: true
multiscale:
  enable: false
copernicus_api:
  base_url: "https://catalogue.dataspace.copernicus.eu/odata/v1"
  token_url: "https://identity.dataspace.copernicus.eu/auth/realms/CDSE/protocol/openid-connect/token"
  client_id: "cdse-public"
logging:
  level: "INFO"
